#!/bin/bash
# builds hpss files and targets to copy them to, upon
# execution of hpss_user.pl file retrieval script

if [ $# -lt 1 ]; then
  echo "Usage: $0 [board#]"
  echo "see online.star.bnl.gov/scaler2013/documentation"
  echo "(hint: board 4 is for luminosity)"
  exit 1
fi

# no. files to put in each list
size=250 

# board number
bd=$1

# daq directory on hpss
hpss_dir="/home/starsink/raw/daq"

# name of file list
lfile="files_to_retrieve"

# last run number retrieved
lastrun=$(head -n1 lastrun)


it=0
file_num=1
file_name="$lfile.$file_num.lst"
> $file_name

while read line; do
  runNum=$(echo $line | awk '{print $2}')
  year=$(echo $runNum | cut -c1-2)
  day=$(echo $runNum | cut -c3-5)
  run=$(echo $runNum | cut -c6-8)
  year=$(echo "($year-1)+2000"|bc)
  #grepstr=$(grep $runNum retrieved_list)
  #if [ -z "$grepstr" ]; then
  if [ $runNum -gt $lastrun ]; then
    let it++
    echo $runNum $year $day $run
    echo "$hpss_dir/$year/$day/$runNum/scaler.run$runNum.bd0$bd.hist.dat /gpfs01/star/scratch/dilks/sca$year/scaler.run$runNum.bd0$bd.hist.dat" >> $file_name
  fi
  if [ $it -eq $size ]; then
    it=0
    let file_num++
    file_name="$lfile.$file_num.lst"
    > $file_name
  fi
done < culled_run_list.txt

if [ $it -eq 0 ]; then rm $file_name; fi
